### ISSUE TITLE
[Feature Request] Prize Tracker: Sort decklist similar to PTCG Live

### ISSUE THREAD

**Issue by GG3Hahn** [Dillonzer/Pokemon_Deck_Utils#32]
I really like having a prize tracker while playing PTCGL, but it's difficult to find the cards that are missing in time because the order of the deck in the prize tracker seems somewhat arbitrary. I would propose to sort the cards the same way that the official client lists them.

As far as I understand the code, the order of cards depends on the response from this API call (which isn't open sourced?):
https://github.com/Dillonzer/Pokemon_Deck_Utils/blob/9bb66225d02d93f350236f1591c8444ec663be8c/scripts.js#L168-L180

From my testing, I believe PTCGL groups the cards like this:
* Pokémon (sorted alphabetically)
* Supporters (sorted primarily by set, resulting groups are sorted alphabetically)
* Items (as above)
* Tools (as above)
* Stadiums (as above)
* Special Energies (as above)
* Basic Energies (sorted primarily by set, resulting groups are sorted by number)

```mermaid
flowchart TD
    p["Pokémon"]
    p --- pp["All\n(alphabetically)"]

    t["Trainer"]
    t --- ts["Supporter\n(by set release date,\nalphabetically)"]
    t --- ti["Item\n(by set release date,\nalphabetically)"]
    t --- tt["Tool\n(by set release date,\nalphabetically)"]
    t --- tst["Stadium\n(by set release date,\nalphabetically)"]

    e["Energy"]
    e --- es["Special\n(by set release date,\nalphabetically)"]
    e --- eb["Basic\n(by set release date,\ncollector number order)"]
```

PTCGL isn't entirely consistent with this pattern (e.g. it would list Archeops after Lugia for me), but I can't see any other discernable rules.

I think this would significally increase the convenience of the tool.

**Comment by Dillonzer** [comment]
Hey -

Yeah my API currently isn't open sourced since I couldn't handle the cost of multiple people making apps with it. There is a good open source api for card data people can use (pokemontcg.io I think? on mobile so can't remember). It didn't do enough for me so I decided to make my own. 

Enough of that - the current order is arbitrary. I should be able to easily sort the return on the client. Worst case I'll update the API to do the sorting.

**Comment by Dillonzer** [comment]
Alright added some sorting similar to what you suggested.
